#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    HOME=${HOME}"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
}

print_vars init-conman

usermod -a -G dialout abc

if [ ! -f /config/conman.conf ]; then
    cp /etc/conman.conf /config/
fi

chown -R abc:abc /config /logs

mkdir -p /var/run/conmand

