#!/usr/bin/with-contenv bash

CONFIG_FILE=/config/conman.conf

devices=()

server () {
    :
}

global () {
    :
}

console () {
    local dev

    devices=()

    while [ $# -gt 0 ]; do
	dev=
	case ${1} in
	    dev=*)
		dev="${1#dev=}"
		;;
	    dev)
		shift
		dev="${1}"
		;;
	esac
	if [[ $dev == /dev* ]]; then
	    devices+=("${dev}")
	fi
	shift
    done
}

sleep 5

while true; do
    echo "Parsing config file"
    . ${CONFIG_FILE}
    echo "Waiting for changes to ${CONFIG_FILE} ${devices[@]}"
    inotifywait -m -s -q \
		-e attrib,modify,move,create,delete \
		--format '%w|%f|%e' \
		${CONFIG_FILE} ${devices[@]} |
	while IFS='|' read -r dir file event; do
	    if [ "${event}" = "MODIFY" -a -L "${dir}${file}" ]; then
		echo "Ignoring change to symlink"
		continue
            fi
	    echo "Restarting conman"
	    s6-svc -r /run/service/conman
	    if [ "${dir}${file}" = "${CONFIG_FILE}" ]; then
		echo "Config file changed: $CONFIG_FILE"
            	break
            fi
	done
    echo "Done"
done
