#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    HOME=${HOME}"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
}

print_vars

usermod -a -G dialout abc

if [ ! -f /config/conman.conf ]; then
    cp /etc/conman.conf /config/
fi

cat > /etc/logrotate.d/conman <<EOF
##
# ConMan Logrotate Configuration
##

/logs/* {
   compress
   missingok
   nocopytruncate
   nocreate
   nodelaycompress
   nomail
   notifempty
   rotate 4
   sharedscripts
   size=5M
   weekly
   postrotate
     /usr/bin/kill -HUP $(cat /var/run/conmand.pid)
   endscript
}
EOF

chown -R abc:abc /config /logs
